name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: g++ Multithread.cpp DevDisk.cpp -o DevDisk.exe

    - name: Run tests
      run: ./DevDisk.exe

    - name: Check code quality
      run: cppcheck Multithread.cpp DevDisk.cpp

    - name: Generate coverage report
      run: gcov Multithread.cpp DevDisk.cpp

    - name: Publish coverage results
      uses: codecov/codecov-action@v2

    - name: Deploy
      if: success()
      run: echo "Deployment steps go here"
