name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubunto-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build
      run: g++ Multithread.cpp -o my_program

    - name: Run tests
      run: ./my_program

    - name: Check code quality
      run: cppcheck Multithread.cpp

    - name: Generate coverage report
      run: gcov Multithread.cpp

    - name: Publish coverage results
      uses: codecov/codecov-action@v2

    - name: Deploy
      if: success()
      run: echo "Deployment steps go here"
